<?php

namespace Mintreu\Layout;

use Illuminate\Support\Facades\Blade;
use Mintreu\Layout\Commands\ManifestCommand;
use Mintreu\Layout\Commands\ThemeCommand;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;
use Mintreu\Layout\Commands\LayoutCommand;

class LayoutServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('layout')
            ->hasConfigFile()
            ->hasViews()
            ->hasMigration('create_layout_table')
            ->hasCommands(LayoutCommand::class,ThemeCommand::class,ManifestCommand::class);
    }


    public function bootingPackage()
    {
        parent::bootingPackage(); // TODO: Change the autogenerated stub
        Blade::component('layout::layout', Layout::class);
    }


}
